--Elena

-- Добавление таблицы с владельцами животных


CREATE TABLE IF NOT EXISTS bot.owners (
  owner_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(20),
  surname varchar (20),
  phone INTEGER,
  animal_id BIGINT NOT NULL,
  animal_name varchar(20),
  animal_type varchar(20),
  PRIMARY KEY (owner_id),
  FOREIGN KEY (animal_id) REFERENCES bot.animal (animal_id)
);

